using System;
using Kasizuki;
using UnityEngine;

public class ControllerShortcutWindow : MonoBehaviour
{
	public void Init(PhotoFaceDataShortcutParent rightHandUI, PhotoFaceDataShortcutParent leftHandUI)
	{
	}

	public void Open()
	{
	}

	public void Close()
	{
	}

	public bool isOpen { get; set; }

	[SerializeField]
	[Range(0.001f, 1f)]
	private float m_FadeSpeed = 0.25f;

	[SerializeField]
	private NGUIWindow m_FadeWindowFaceShortcut;

	[SerializeField]
	private NGUIWindow m_FadeWindowMotionShortcut;

	[SerializeField]
	private NGUIWindow m_FadeWindowCalibration;

	[SerializeField]
	private NGUIWindow m_FadeWindowConfig;

	[SerializeField]
	private NGUIWindow m_FadeWindowGeneralObject;

	[SerializeField]
	private NGUIWindow m_FadeWindowMainMenu;

	[SerializeField]
	private NGUIWindow m_FadeWindowParent;

	private UIButton m_FadeWindowHideButton;

	[SerializeField]
	private UIWFTabPanel m_ParentButtonMainMenu;
}
