using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class _TS : MonoBehaviour
{
	private void Awake()
	{
		_TS.mode = "root";
	}

	private void Start()
	{
		GameObject.Find("GUI Text ResKeyTEST").GetComponent<GUIText>().text = string.Empty;
		this.opinfo2 = this.readme.text;
		StringReader stringReader = new StringReader(this.opinfo2);
		this.opinfo2_1 = stringReader.ReadLine();
		stringReader.Close();
	}

	public static bool Active;

	public static string mode = string.Empty;

	public List<string> dirsMotion;

	public static List<byte> listVoice = null;

	public static float startVoiceTime = 0f;

	public static Dictionary<string, string> DebugMenu = new Dictionary<string, string>();

	public static int LeakTestTgl = 0;

	public static int LeakTestTgl2 = 0;

	private string opinfo2 = string.Empty;

	private string opinfo2_1 = string.Empty;

	private float OnloadTime;

	public static Vector3 CameraR = new Vector3(0f, 0f, 0f);

	private Vector3 CameraV = new Vector3(0f, 0f, 7f);

	private Vector3 CameraR_ = new Vector3(0f, 0f, 0f);

	private Vector3 CameraV_ = new Vector3(0f, 0f, 7f);

	private Vector3 CameraTgt = new Vector3(0f, 2f, 0f);

	private Vector3 CameraTgt_ = new Vector3(0f, 2f, 0f);

	public static bool boInMenuWindow;

	public Texture TestTexture;

	public TextAsset readme;

	public static string reqChangeBG = null;

	public static int kizu_test_cnt = 0;

	private SortedDictionary<string, int> FaceMorphList;

	public static float TestVal = 0.25f;

	public static float TestVal2 = 0.22f;

	public static float TestVal3 = 0.5f;

	public static float TestAshi = 0f;

	public static float TestVal_M = 1f;

	public static float TestVal2_M = 1f;

	public static float TestVal3_M = 1f;

	public static float TestVal4_M = 1f;

	public static bool TestCheckBox = false;

	public Transform trasTest;

	private GUIStyle guiStyle;

	private float Motion_Weight = 1f;

	public AudioClip audio_clip;

	private Vector2 scrollPositionMotion = Vector2.zero;

	public GUISkin guiskin;

	public string BackDir = string.Empty;

	public static bool Active_old = false;

	public static int testcount = 0;
}
